name: 'shailahir/kubernetes-action'
description: 'Simple Kubernetes Deployment tool'
inputs:
  testInput:
    description: 'Testing the Input'
    required: true
    default: 'Hello'
outputs:
  time:
    description: 'System time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testInput }}
