name: 'shailahir/kubernetes-action'
description: 'Simple Kubernetes Deployment tool'
inputs:
  kubeCofig:
    description: 'KubeConfig for connectng to kubernetes instance'
    required: true
outputs:
  time:
    description: 'System time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.testInput }}

branding:
  icon: arrow-right
  color: blue
